from langchain_openai import ChatOpenAI
from dotenv import load_dotenv
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import PydanticOutputParser
from pydantic import BaseModel, Field


load_dotenv()


# Initialize the LLM
model = ChatOpenAI(model="gpt-3.5-turbo")


# Define the expected output structure using Pydantic
class Person(BaseModel):
    name: str = Field(description="The name of the person")
    age: int = Field(description="The age of the person")
    occupation: str = Field(description="The occupation of the person")


# Create parser using the Pydantic model
# It validates the LLM response according to the Person schema
parser = PydanticOutputParser(pydantic_object=Person)


# Create prompt template
template = PromptTemplate(
    template="""
    Generate the name, age and occupation of a famous person from {country}.

    {format_instructions}
    """,

    # Variable that will be provided when invoking the chain
    input_variables=["country"],

    # Automatically adds instructions generated by PydanticOutputParser
    # to tell the LLM the required output format
    partial_variables={
        "format_instructions": parser.get_format_instructions()
    }
)


# LCEL chain:
# PromptTemplate → LLM → PydanticOutputParser
chain = template | model | parser


# Pass the country to the prompt
response = chain.invoke({
    "country": "Pakistan"
})


# response is now a validated Person Pydantic object
print(response)